name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        include:
        - buildPlatform: win
          os: windows-latest
        - buildPlatform: linux
          os: ubuntu-latest
        - buildPlatform: mac
          os: macOS-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package jpackage:jpackage
    - name: Upload installer
      uses: actions/upload-artifact@v3
      with:
        name: Convolut0r-${{ matrix.buildPlatform }}
        path: target/jpackage/*
    - name: show directory structure if failed
      run: find target
      if: ${{ failure() }}